import '../models/event_model.dart';
import '../models/user_model.dart';

const List<String> kCategories = [
  'All',
  'Academic',
  'Social',
  'Sports',
  'Career',
  'Arts'
];

const List<String> kCampusLocations = [
  '1 · Administration Building',
  '2 · School of Languages',
  '3 · Sabancı Business School',
  '4 · Faculty of Engineering and Natural Sciences',
  '5 · Faculty of Arts and Social Sciences',
  '6 · Art Studios',
  '7 · Information Center',
  '8 · SUNUM',
  '9 · Main Gate and Security',
  '10 · University Center - Cafeteria',
  '11 · Cinema Hall',
  '12 · Central Plant',
  '13 · Performing Arts Center (SGM)',
  '14 · Amphitheater',
  '15 · President\'s House',
  '16 · Health Center and Social Services',
  '17 · Nursery School',
  '18 · Student Clubs Buildings',
  '19 · Entrepreneurship and Incubation Center',
  '20 · Treatment Plant',
  '21 · Sports Center',
  '22 · Tennis Court',
  '23 · Football Field',
  '24 · Faculty Housing',
  '25 · Student Dormitories',
];

const Map<String, Map<String, String>> kCampusLocationDetails = {
  '1 · Administration Building': {
    'building': 'Administration Building',
    'floor': '1',
    'room': 'Main Hall',
    'label': '1 · Administration Building',
  },
  '2 · School of Languages': {
    'building': 'School of Languages',
    'floor': '1',
    'room': 'Seminar Hall',
    'label': '2 · School of Languages',
  },
  '3 · Sabancı Business School': {
    'building': 'Sabancı Business School',
    'floor': '1',
    'room': 'Lecture Hall',
    'label': '3 · Sabancı Business School',
  },
  '4 · Faculty of Engineering and Natural Sciences': {
    'building': 'Faculty of Engineering and Natural Sciences',
    'floor': 'B',
    'room': '3',
    'label': '4 · Faculty of Engineering and Natural Sciences',
  },
  '5 · Faculty of Arts and Social Sciences': {
    'building': 'Faculty of Arts and Social Sciences',
    'floor': '1',
    'room': 'A1',
    'label': '5 · Faculty of Arts and Social Sciences',
  },
  '6 · Art Studios': {
    'building': 'Art Studios',
    'floor': '1',
    'room': 'Studio A',
    'label': '6 · Art Studios',
  },
  '7 · Information Center': {
    'building': 'Information Center',
    'floor': '1',
    'room': 'Seminar Room',
    'label': '7 · Information Center',
  },
  '8 · SUNUM': {
    'building': 'SUNUM',
    'floor': '1',
    'room': 'Conference Room',
    'label': '8 · SUNUM',
  },
  '9 · Main Gate and Security': {
    'building': 'Main Gate and Security',
    'floor': 'Outdoor',
    'room': 'Entrance',
    'label': '9 · Main Gate and Security',
  },
  '10 · University Center - Cafeteria': {
    'building': 'University Center',
    'floor': '1',
    'room': 'Cafeteria Hall',
    'label': '10 · University Center - Cafeteria',
  },
  '11 · Cinema Hall': {
    'building': 'Cinema Hall',
    'floor': '1',
    'room': 'Main Hall',
    'label': '11 · Cinema Hall',
  },
  '12 · Central Plant': {
    'building': 'Central Plant',
    'floor': '1',
    'room': 'Meeting Room',
    'label': '12 · Central Plant',
  },
  '13 · Performing Arts Center (SGM)': {
    'building': 'Performing Arts Center (SGM)',
    'floor': '1',
    'room': 'Main Stage',
    'label': '13 · Performing Arts Center (SGM)',
  },
  '14 · Amphitheater': {
    'building': 'Amphitheater',
    'floor': 'Outdoor',
    'room': 'Stage Area',
    'label': '14 · Amphitheater',
  },
  '15 · President\'s House': {
    'building': 'President\'s House',
    'floor': '1',
    'room': 'Reception Hall',
    'label': '15 · President\'s House',
  },
  '16 · Health Center and Social Services': {
    'building': 'Health Center and Social Services',
    'floor': '1',
    'room': 'Conference Room',
    'label': '16 · Health Center and Social Services',
  },
  '17 · Nursery School': {
    'building': 'Nursery School',
    'floor': 'Ground',
    'room': 'Activity Hall',
    'label': '17 · Nursery School',
  },
  '18 · Student Clubs Buildings': {
    'building': 'Student Clubs Buildings',
    'floor': '1',
    'room': 'Event Room',
    'label': '18 · Student Clubs Buildings',
  },
  '19 · Entrepreneurship and Incubation Center': {
    'building': 'Entrepreneurship and Incubation Center',
    'floor': '1',
    'room': 'Workshop Hall',
    'label': '19 · Entrepreneurship and Incubation Center',
  },
  '20 · Treatment Plant': {
    'building': 'Treatment Plant',
    'floor': '1',
    'room': 'Operations Room',
    'label': '20 · Treatment Plant',
  },
  '21 · Sports Center': {
    'building': 'Sports Center',
    'floor': '1',
    'room': 'Court A',
    'label': '21 · Sports Center',
  },
  '22 · Tennis Court': {
    'building': 'Tennis Court',
    'floor': 'Outdoor',
    'room': 'Court',
    'label': '22 · Tennis Court',
  },
  '23 · Football Field': {
    'building': 'Football Field',
    'floor': 'Outdoor',
    'room': 'Field',
    'label': '23 · Football Field',
  },
  '24 · Faculty Housing': {
    'building': 'Faculty Housing',
    'floor': 'Ground',
    'room': 'Common Area',
    'label': '24 · Faculty Housing',
  },
  '25 · Student Dormitories': {
    'building': 'Student Dormitories',
    'floor': 'Ground',
    'room': 'Common Hall',
    'label': '25 · Student Dormitories',
  },
};

const Map<String, String> kLegacyLocationAliases = {
  'Engineering Hall B3': '4 · Faculty of Engineering and Natural Sciences',
  'Student Center Auditorium': '13 · Performing Arts Center (SGM)',
  'Main Conference Center': '10 · University Center - Cafeteria',
  'Indoor Sports Complex': '21 · Sports Center',
  'Lecture Hall A1': '5 · Faculty of Arts and Social Sciences',
  'Main Lawn': '10 · University Center - Cafeteria',
  'Student Center Courtyard': '10 · University Center - Cafeteria',
  'Faculty of Engineering and Natural Sciences':
      '4 · Faculty of Engineering and Natural Sciences',
  'Performing Arts Center (SGM)': '13 · Performing Arts Center (SGM)',
  'Student Clubs Buildings': '18 · Student Clubs Buildings',
  'University Center - Cafeteria': '10 · University Center - Cafeteria',
  'Cinema Hall': '11 · Cinema Hall',
  'Sports Center': '21 · Sports Center',
  'Tennis Court': '22 · Tennis Court',
  'Football Field': '23 · Football Field',
  'Art Studios': '6 · Art Studios',
  'Information Center': '7 · Information Center',
  'Health Center and Social Services': '16 · Health Center and Social Services',
  'Student Dormitories': '25 · Student Dormitories',
  'Library Room 204': '7 · Information Center',
  'Main Gate': '9 · Main Gate and Security',
  'Meet at Main Gate': '9 · Main Gate and Security',
  'Central Campus Green': '14 · Amphitheater',
};

const List<String> kDepartments = [
  'Computer Science',
  'Industrial Engineering',
  'Electronics Engineering',
  'Mechatronics',
  'Management',
  'Economics',
  'Psychology',
  'Sociology',
  'Visual Arts & Communication',
  'Political Science',
  'Mathematics',
  'Physics',
  'Molecular Biology',
];

final Map<String, User> kDemoSeeds = {
  'student@sabanciuniv.edu': const User(
      role: 'student',
      firstName: 'Emir',
      lastName: 'Mirza',
      dept: 'Computer Science'),
  'cssociety@sabanciuniv.edu': const User(
      role: 'admin',
      firstName: 'CS',
      lastName: 'Society',
      dept: 'Club Administrator',
      clubName: 'CS Society'),
};

List<Event> buildEventList() => [
      Event(
        id: 1,
        title: 'Spring Hackathon 2026',
        club: 'CS Society',
        clubId: 'cssociety',
        date: 'Apr 12',
        time: '09:00',
        loc: '4 · Faculty of Engineering and Natural Sciences',
        cat: 'Academic',
        desc:
            '48-hour coding marathon. Build innovative solutions with your team. Prizes for top 3 teams. Food and drinks provided throughout.',
        rsvp: 142,
        saved: false,
        building: 'Faculty of Engineering and Natural Sciences',
        floor: 'B',
        room: '3',
        posterUrl: 'assets/images/poster_datamind.jpg',
      ),
      Event(
        id: 2,
        title: 'Open Mic Night',
        club: 'Music Club',
        clubId: 'music',
        date: 'Apr 10',
        time: '19:30',
        loc: '13 · Performing Arts Center (SGM)',
        cat: 'Arts',
        desc:
            'Show off your talent or enjoy the performances. Sign-ups at the door. All genres welcome.',
        rsvp: 89,
        saved: true,
        building: 'Performing Arts Center (SGM)',
        floor: '1',
        room: 'Auditorium',
        posterUrl: 'assets/images/poster_openmic_microphone.png',
      ),
      Event(
        id: 3,
        title: 'Career Fair: Tech',
        club: 'Career Office',
        clubId: 'career',
        date: 'Apr 15',
        time: '10:00',
        loc: '10 · University Center - Cafeteria',
        cat: 'Career',
        desc:
            'Meet recruiters from top tech companies. Bring your resume and dress smart casual.',
        rsvp: 310,
        saved: false,
        building: 'University Center - Cafeteria',
        floor: '1',
        room: 'Main Hall',
        posterUrl: 'assets/images/poster_networking_fair.jpg',
      ),
      Event(
        id: 4,
        title: '5v5 Basketball',
        club: 'Sports Union',
        clubId: 'sports',
        date: 'Apr 18',
        time: '14:00',
        loc: '21 · Sports Center',
        cat: 'Sports',
        desc:
            'Register your team of 5. Double elimination bracket. Trophies for champions.',
        rsvp: 64,
        saved: true,
        building: 'Sports Center',
        floor: '1',
        room: 'Court A',
      ),
      Event(
        id: 5,
        title: 'AI & Ethics Panel',
        club: 'Philosophy Society',
        clubId: 'philosophy',
        date: 'Apr 20',
        time: '16:00',
        loc: '5 · Faculty of Arts and Social Sciences',
        cat: 'Academic',
        desc:
            'Faculty-led discussion on the ethical implications of generative AI in academic and public life.',
        rsvp: 56,
        saved: false,
        building: 'Faculty of Arts and Social Sciences',
        floor: 'A',
        room: '1',
        posterUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=450&fit=crop',
      ),
      Event(
        id: 6,
        title: 'Spring Picnic & BBQ',
        club: 'Student Government',
        clubId: 'stugovt',
        date: 'Apr 22',
        time: '12:00',
        loc: '14 · Amphitheater',
        cat: 'Social',
        desc:
            'Free food, lawn games, and live DJ. The perfect study break before finals.',
        rsvp: 230,
        saved: false,
        building: 'Amphitheater',
        floor: '—',
        room: 'Outdoor Lawn',
        posterUrl: 'assets/images/poster_menu.jpg',
      ),
      Event(
        id: 7,
        title: 'Photography Walk',
        club: 'Photo Club',
        clubId: 'photo',
        date: 'Apr 14',
        time: '15:00',
        loc: '9 · Main Gate and Security',
        cat: 'Arts',
        desc:
            'Golden hour campus walk. Bring any camera. Best shots featured on Instagram.',
        rsvp: 38,
        saved: false,
        building: 'Main Gate and Security',
        floor: '—',
        room: '—',
      ),
      Event(
        id: 8,
        title: 'Resume Workshop',
        club: 'Career Office',
        clubId: 'career',
        date: 'Apr 11',
        time: '13:00',
        loc: '7 · Information Center',
        cat: 'Career',
        desc:
            'One-on-one resume reviews with industry mentors. Limited spots available.',
        rsvp: 45,
        saved: true,
        building: 'Information Center',
        floor: '2',
        room: '204',
        posterUrl: 'assets/images/poster_if100_workshop.jpg',
      ),
    ];
